<?php
/* vim: set shiftwidth=2 tabstop=2 softtabstop=2: */

function gitlabgithubbridge_mail($key, &$message, $params) {
  switch ($key) {
    case 'merge_objects_only':
      $message['subject'] = 'CiviCARROT failure report';
      $message['body'][] = 'Only merge_request objects are allowed as webhook triggers and the merge request must be in an open state.';
      break;

    case 'trigger_failure':
      $message['subject'] = 'CiviCARROT failure report';
      $message['body'][] = 'An error occurred starting the workflow:';
      $message['body'][] = $params['result'];
      break;
  }
}
